#!/bin/bash

# This will help install all requirements for running the program

sudo apt-get install python3 python3-pip cups-pdf
sudo pip3 install re selenium pyvirtualdisplay time os getpass beautifulsoup4 platform